### PR TITLE
Filter out non-header files from Compile Source phase

### LINKED ISSUE #414: Bug: Non-processable file warning for non-source code files
## Describe the bug
Building in Xcode can result in warnings for files not recognized by Xcode, included in sources: 

image

## Reproduction steps

Include an "irregular" file in `srcs`, such as a `.inc`

## Expected behavior

The file is not included in the compile sources phase

## Versions
- Bazel:5.1.0
- rules_xcodeproj: <experimental `build_mode = "bazel"` >
- rules_apple: 
- rules_swift: 

## Additional context

Built using experimental Bazel build model

### PR DESCRIPTION
**Pull request by maxwellE**
Fixes #414.

### CODE REVIEW

File: tools/generator/src/Generator+AddTargets.swift [hunk 1]
```diff
@@ -146,7 +146,7 @@ Product for target "\(id)" not found in `products`
             return nil
         }
 
-        let publicHeaders = inputs.hdrs
+        let publicHeaders = inputs.hdrs.filter(\.path.isHeader)
```
Comment (brentleyjones) [inline tools/generator/src/Generator+AddTargets.swift:149]: I don't think this is needed? Only the `inputs.nonArcSrcs` and `inputs.srcs` filters.

File: tools/generator/src/Generator+AddTargets.swift [hunk 2]
```diff
@@ -193,7 +193,9 @@ File "\(headerFile.filePath)" not found in `files`
             .forcedBazelCompileFiles(buildMode: buildMode)
         let sources = forcedBazelCompileFiles.map(SourceFile.init) +
             inputs.srcs.map(SourceFile.init) +
-            inputs.nonArcSrcs.map { filePath in
+            inputs.nonArcSrcs
+                .filter { !$0.path.isHeader }
```
Comment (brentleyjones) [inline tools/generator/src/Generator+AddTargets.swift:197]: Can you add this to `inputs.srcs` as well?

File: tools/generator/src/Generator+AddTargets.swift [hunk 3]
```diff
@@ -193,7 +193,9 @@ File "\(headerFile.filePath)" not found in `files`
...
+                .map { filePath in
                 return SourceFile(
```
Comment (brentleyjones) [inline tools/generator/src/Generator+AddTargets.swift:199]: Can you indent this whole statement up one? Also the closing `}`.

**Review by brentleyjones — APPROVED** [review]

**Comment by brentleyjones** [comment]
Looks like you need to update the fixtures: https://github.com/buildbuddy-io/rules_xcodeproj/blob/main/CONTRIBUTING.md#developing

File: tools/generator/src/Generator+AddTargets.swift [hunk 4]
```diff
@@ -192,8 +192,8 @@ File "\(headerFile.filePath)" not found in `files`
         let forcedBazelCompileFiles = outputs
             .forcedBazelCompileFiles(buildMode: buildMode)
         let sources = forcedBazelCompileFiles.map(SourceFile.init) +
-            inputs.srcs.map(SourceFile.init) +
-            inputs.nonArcSrcs.map { filePath in
+            inputs.srcs.filter { !$0.path.isHeader }.map(SourceFile.init) +
```
Comment (jpsim) [inline tools/generator/src/Generator+AddTargets.swift:195]: Minor optional nit, this could be nicer as an extension:

```swift
private extension Sequence where Element == FilePath {
    var excludingHeaders: [Element] {
        self.filter { !$0.path.isHeader }
    }
}
```

**Review by jpsim — APPROVED** [review]

**Comment by brentleyjones** [comment]
Some changes are needed in `Fixtures.swift`. You should be able to run the tests locally with `bazel test --config=cache //tools/...`.

**Comment by tinder-maxwellelliott** [comment]
> Some changes are needed in `Fixtures.swift`. You should be able to run the tests locally with `bazel test --config=cache //tools/...`.

On it now

**Comment by maxwellE** [comment]
> Some changes are needed in `Fixtures.swift`. You should be able to run the tests locally with `bazel test --config=cache //tools/...`.

How do you debug these `AssertNoDifferences`, I only get a subset of the change and I cannot easily tell which target owns the added `PBXObjectReference`

**Comment by brentleyjones** [comment]
Yeah, sometimes the diffs hide context. For these though, you know you are removing files from the `Compile Sources`, so you'll need to remove things from `PBXSourcesBuildPhase` initializers (or the phases all together) for targets that had headers there. One example is `PBXBuildFile(file: elements["z.h"]!),`.

**Review by brentleyjones — APPROVED** [review]
