### PR TITLE
Send linker flags with a response file to work around large argument lists

### LINKED ISSUE #663: Bug: Xcode crashes when building a project with too many arguments in a build setting
## Describe the bug
Xcode crashes when triggering a build in a very big project with too many arguments in a build setting. This bug was exposed by https://github.com/buildbuddy-io/rules_xcodeproj/pull/602 in our project given the many `-Wl,-add_ast_path,...` set in `OTHER_LD_FLAGS`. The Exception looks like we're running into a command-line length limit:
```
** INTERNAL ERROR: Uncaught exception **
Uncaught Exception: Couldn't posix_spawn: error 7
Stack:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   -[NSConcreteTask launchWithDictionary:error:] (in Foundation)
  3   __46-[IDEShellScriptExecutionActionOperation main]_block_invoke.308 (in IDEStandardExecutionActionsCore)
  4   __DVT_CALLING_CLIENT_BLOCK__ (in DVTFoundation)
  5   ___DVTAsyncPerformBlockOnMainRunLoop_block_invoke (in DVTFoundation)
  6   __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ (in CoreFoundation)
  7   __CFRunLoopDoBlocks (in CoreFoundation)
  8   __CFRunLoopRun (in CoreFoundation)
  9   CFRunLoopRunSpecific (in CoreFoundation)
 10   CFRunLoopRun (in CoreFoundation)
 11   -[Xcode3CommandLineBuildTool _buildWithTimingSection:] (in Xcode3Core)
 12   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
 13   XcodeBuildMain (in libxcodebuildLoader.dylib)
 14   start (in dyld)
```

One possible fix can be to use a response file instead of passing each argument separately with the following syntax: `-Wl,@some/path/to/file`

## Reproduction steps
Generate a project big enough with likely thousands of targets and run a build. Xcode will immediately crash.

## Expected behavior
Xcode should run the build without crashing like before https://github.com/buildbuddy-io/rules_xcodeproj/pull/602 in big projects.

## Versions
- Bazel: 5.2
- rules_xcodeproj: Right after https://github.com/buildbuddy-io/rules_xcodeproj/pull/602

### PR DESCRIPTION
**Pull request by brentleyjones**
Fixes #663.

### CODE REVIEW

File: tools/generator/src/Generator/AddTargets.swift [hunk 1]
```diff
@@ -169,6 +174,32 @@ Product for target "\(key)" not found in `products`
...
+            name: "Create link.params",
+            inputPaths: [linkParamsFile],
+            outputPaths: ["$(DERIVED_FILE_DIR)/link.params"],
+            shellScript: #"""
+sed \
+  -e "s|^\(.*\)\$(BUILD_DIR)\(.*\)\$|\"\1${BUILD_DIR}\2\"|g" \
+  -e "s|^\(.*\)\$(DEVELOPER_DIR)\(.*\)\$|\"\1${DEVELOPER_DIR}\2\"|g" \
+  "$SCRIPT_INPUT_FILE_0" > "$SCRIPT_OUTPUT_FILE_0"
+
+"""#,
```
Comment (brentleyjones) [inline tools/generator/src/Generator/AddTargets.swift:195]: Build env variables aren't available once clang has this file, so we need to process the link.params first before handing it off to clang.

**Review by BalestraPatrick — APPROVED** [review]
